"use client";

import { useCallback, useEffect, useState } from "react";

type ChatView = { conversationId: string; node: { type: string; content: string; captureType: string | null }; options: { id: string; label: string }[]; messages: { sender: string; content: string }[]; status: string; branding: string | number | boolean | null | Record<string, unknown> | unknown[]; routeHint?: string };
function sessionKey(widgetId: string) { return `ltr_chat_session_${widgetId}`; }
function renewSessionId(widgetId: string) { const value = crypto.randomUUID(); sessionStorage.setItem(sessionKey(widgetId), value); return value; }
function sessionId(widgetId: string) { return sessionStorage.getItem(sessionKey(widgetId)) ?? renewSessionId(widgetId); }

export function ChatWidget({ widgetId, floating = false, endpoint = "/api/chatbot" }: { widgetId: string; floating?: boolean; endpoint?: string }) {
  const [view, setView] = useState<ChatView | null>(null); const [open, setOpen] = useState(!floating); const [text, setText] = useState(""); const [error, setError] = useState("");
  const call = useCallback(async (body: Record<string, unknown>) => { setError(""); const activeSessionId = body.action === "restart" ? renewSessionId(widgetId) : sessionId(widgetId); const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ widgetId, sessionId: activeSessionId, ...body }) }); const data = await response.json(); if (!response.ok) { setError(data.error ?? "Chat is unavailable."); return; } setView(data); }, [endpoint, widgetId]);
  useEffect(() => { if (!open || view) return; const timer = window.setTimeout(() => { void call({ action: "start" }); }, 0); return () => window.clearTimeout(timer); }, [call, open, view]);
  const primary = view?.branding && typeof view.branding === "object" && !Array.isArray(view.branding) && typeof view.branding.primary_color === "string" ? view.branding.primary_color : "#2563eb";
  return <div className={floating ? "fixed bottom-5 right-5 z-50" : "mx-auto w-full max-w-sm p-3"}>
    {floating && !open ? <button aria-label="Open chat" className="rounded-full px-5 py-3 font-semibold text-white shadow-lg" onClick={() => setOpen(true)} style={{ backgroundColor: primary }}>Chat</button> : null}
    {open && <section className="w-[min(92vw,380px)] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl"><header className="flex items-center justify-between px-4 py-3 text-white" style={{ backgroundColor: primary }}><strong>Chat with us</strong><div className="flex gap-2"><button aria-label="Restart chat" onClick={() => void call({ action: "restart" })}>↻</button>{floating && <button aria-label="Close chat" onClick={() => setOpen(false)}>×</button>}</div></header><div className="max-h-[55vh] min-h-64 space-y-3 overflow-y-auto p-4">{view?.messages.map((message, index) => <p className={`w-fit max-w-[90%] rounded-xl px-3 py-2 text-sm ${message.sender === "visitor" ? "ml-auto bg-blue-50" : "bg-slate-100"}`} key={`${index}-${message.content}`}>{message.content}</p>)}{error && <p className="text-sm text-red-700">{error}</p>}</div>{view?.options.length ? <div className="flex flex-wrap gap-2 border-t p-3">{view.options.map((option) => <button className="rounded-lg border px-3 py-1.5 text-sm" key={option.id} onClick={() => void call({ action: "select", edgeId: option.id })}>{option.label}</button>)}</div> : null}{view?.node.type === "capture" || view?.status === "active" ? <form className="flex gap-2 border-t p-3" onSubmit={(event) => { event.preventDefault(); if (text.trim()) { void call({ action: "text", text }); setText(""); } }}><input aria-label="Chat message" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm" onChange={(event) => setText(event.target.value)} placeholder={view?.node.type === "capture" ? "Type your answer" : "Ask a question"} value={text} /><button className="rounded-lg px-3 py-2 text-sm text-white" style={{ backgroundColor: primary }}>Send</button></form> : null}</section>}
  </div>;
}
