"use client";

import { useActionState } from "react";
import { createIntervention, resetStarterChatbot, resolveIntervention, type OperatorActionState } from "./actions";
const initial: OperatorActionState = { error: null };
function Notice({ state }: { state: OperatorActionState }) { return state.error ? <p className="text-sm text-red-700">{state.error}</p> : state.message ? <p className="text-sm text-emerald-700">{state.message}</p> : null; }
export function ResetStarterChatbotForm({ tenantId }: { tenantId: string }) { const [state, action, pending] = useActionState(resetStarterChatbot, initial); return <form action={action} className="mt-3 grid gap-2"><input name="tenantId" type="hidden" value={tenantId} /><label className="text-sm">Type <strong>RESET</strong> to replace the existing chatbot<input className="mt-1 w-full rounded border px-3 py-2" name="confirm" /></label><button className="w-fit rounded bg-red-700 px-3 py-2 text-sm text-white disabled:opacity-60" disabled={pending}>Apply template starter chatbot</button><Notice state={state} /></form>; }
export function InterventionForm({ tenantId, leadId, conversationId }: { tenantId: string; leadId?: string | null; conversationId?: string | null }) { const [state, action, pending] = useActionState(createIntervention, initial); return <form action={action} className="grid gap-2 rounded-lg border border-amber-200 bg-amber-50 p-4"><input name="tenantId" type="hidden" value={tenantId} /><input name="leadId" type="hidden" value={leadId ?? ""} /><input name="conversationId" type="hidden" value={conversationId ?? ""} /><label className="text-sm font-medium">Reason for internal intervention<textarea className="mt-1 w-full rounded border px-3 py-2" name="reason" rows={3} required /></label><button className="w-fit rounded bg-amber-700 px-3 py-2 text-sm text-white disabled:opacity-60" disabled={pending}>Open intervention</button><Notice state={state} /></form>; }
export function ResolveInterventionForm({ id }: { id: string }) { const [state, action, pending] = useActionState(resolveIntervention, initial); return <form action={action} className="mt-2 flex flex-wrap gap-2"><input name="id" type="hidden" value={id} /><input className="min-w-48 flex-1 rounded border px-3 py-2 text-sm" name="notes" placeholder="Resolution notes (optional)" /><button className="rounded border px-3 py-2 text-sm disabled:opacity-60" disabled={pending}>Resolve</button><Notice state={state} /></form>; }
