"use client";
import { useActionState } from "react";
import { saveChatbotEdge, saveChatbotNode, saveChatbotSettings, type ChatbotSettingsState } from "./actions";
import type { TableRow } from "@/lib/supabase/database.types";
const initial: ChatbotSettingsState = { error: null }; const input = "w-full rounded-lg border border-slate-300 px-3 py-2 text-sm";
function Notice({ state }: { state: ChatbotSettingsState }) { return state.error ? <p className="text-sm text-red-700">{state.error}</p> : state.message ? <p className="text-sm text-emerald-700">{state.message}</p> : null; }
export function ChatbotSettingsForm({ config, editable }: { config: TableRow<"chatbot_configs">; editable: boolean }) { const [state, action, pending] = useActionState(saveChatbotSettings, initial); const branding = config.branding && typeof config.branding === "object" && !Array.isArray(config.branding) ? config.branding : {}; return <form action={action} className="grid gap-4"> <label>Name<input className={input} defaultValue={config.name} disabled={!editable} name="name" /></label><label>Welcome message<textarea className={input} defaultValue={config.welcome_message} disabled={!editable} name="welcome" rows={2} /></label><label>Fallback message<textarea className={input} defaultValue={config.fallback_message} disabled={!editable} name="fallback" rows={2} /></label><label>Lead confirmation<textarea className={input} defaultValue={config.confirmation_message} disabled={!editable} name="confirmation" rows={2} /></label><div className="grid gap-3 sm:grid-cols-2"><label>Primary colour<input className={input} defaultValue={typeof branding.primary_color === "string" ? branding.primary_color : "#2563eb"} disabled={!editable} name="color" /></label><label>Button position<select className={input} defaultValue={typeof branding.position === "string" ? branding.position : "right"} disabled={!editable} name="position"><option value="right">Right</option><option value="left">Left</option></select></label></div><div className="flex gap-4 text-sm"><label><input defaultChecked={config.enabled} disabled={!editable} name="enabled" type="checkbox" /> Enabled</label><label><input defaultChecked={config.lead_capture_enabled} disabled={!editable} name="leadCapture" type="checkbox" /> Lead capture</label><label>Status <select disabled={!editable} name="status"><option value="draft">Draft</option><option selected={config.status === "published"} value="published">Published</option></select></label></div>{editable && <button className="rounded-lg bg-blue-700 px-3 py-2 text-sm text-white disabled:opacity-60" disabled={pending}>Save chatbot</button>}<Notice state={state} /></form>; }
export function NodeForm({ node, editable }: { node: TableRow<"chatbot_nodes">; editable: boolean }) { const [state, action, pending] = useActionState(saveChatbotNode, initial); return <form action={action} className="grid gap-2 rounded-lg border p-3"><input name="id" type="hidden" value={node.id} /><p className="text-xs text-slate-500">{node.key} · {node.node_type}</p><textarea className={input} defaultValue={node.content} disabled={!editable} name="content" rows={2} />{editable && <button className="w-fit rounded border px-2 py-1 text-sm" disabled={pending}>Save text</button>}<Notice state={state} /></form>; }
export function EdgeForm({ edge, editable }: { edge: TableRow<"chatbot_edges">; editable: boolean }) { const [state, action, pending] = useActionState(saveChatbotEdge, initial); if (!edge.label) return null; return <form action={action} className="flex gap-2"><input name="id" type="hidden" value={edge.id} /><input className={input} defaultValue={edge.label} disabled={!editable} name="label" />{editable && <button className="rounded border px-2 text-sm" disabled={pending}>Save</button>}<Notice state={state} /></form>; }
